spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_db
    username: crypto_app_user
    password: passw0rd
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
